---

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE

:release_build:
  :output: libPIC24shared.a
  :use_assembly: TRUE

:paths:
  :source:
    - +:./src/**
    - +:../portable/**

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines
    - __PIC24F16KA101__
    - UNITY_INT_WIDTH=16
    - CMOCK_MEM_INDEX_TYPE=uint16_t
    - CMOCK_MEM_PTR_AS_INT=uint16_t
    - CMOCK_MEM_ALIGN=1
    - CMOCK_MEM_SIZE=8192
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:tools:
  :release_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24F16KA101
      - -x c
      - -c
      - "${1}"
      - -o ${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -Wall
      #- -Werror
      - -O1
      #- -g debug
  :release_assembler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24F16KA101
      - -c
      - ${1}
      - -o ${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -Wall
      - -O1
      - -Wa,--no-relax
  :release_linker:
    :executable: xc16-ar
    :arguments:
      - qc
      - ${2}
      - ${1}
:plugins:
  :load_paths:
    - ../../../tools/ceedling/plugins
    - ../../../tools/ceedling-plugins
  :enabled:
    - stdout_pretty_tests_report
...
